export enum UserMutationTypes {
	/** 设置Token */
	SET_TOKEN = 'SET_TOKEN',

	SET_INTRODUCTION = 'SET_INTRODUCTION',
	SET_NAME = 'SET_NAME',
	SET_AVATAR = 'SET_AVATAR',
	SET_ROLES = 'SET_ROLES',
	SET_PERMISSIONS = 'SET_PERMISSIONS'
}
